// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ShipManagementService.Infrastructure.Database;
using System;

namespace ShipManagementService.Infrastructure.Migrations
{
    [DbContext(typeof(ShipManagementDbContext))]
    partial class ShipManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShipManagementService.Core.Models.Customer", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("PostalCode")
                        .IsRequired();

                    b.Property<string>("Residence")
                        .IsRequired();

                    b.HasKey("Email");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ShipManagementService.Core.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("Price");

                    b.Property<Guid?>("ShipId");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("ShipManagementService.Core.Models.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Ship");
                });

            modelBuilder.Entity("ShipManagementService.Core.Models.Service", b =>
                {
                    b.HasOne("ShipManagementService.Core.Models.Ship")
                        .WithMany("ShipServices")
                        .HasForeignKey("ShipId");
                });
#pragma warning restore 612, 618
        }
    }
}
